# Problem set 6: Solving the Solow model

In [1]:
import numpy as np
from scipy import linalg
from scipy import optimize
import sympy as sm

# Tasks

## Solving matrix equations I

In [2]:
np.random.seed(1900)
n = 5
A = np.random.uniform(size=(n,n))
b = np.random.uniform(size=n)
c = np.random.uniform(size=n)
d = np.random.uniform(size=n)

**Question A:** Find the determinant of $[A \cdot A]^{-1}$

In [5]:
# write your code here
mult = A@A
inv = linalg.inv(mult)
det = linalg.det(inv)
det

13132.548734460965

**Answer:** see A1.py

**Question B:** Solve the following equation systems directly using **scipy**.

$$
\begin{aligned}
Ax &= b \\
Ax &= c \\
Ax &= d 
\end{aligned}
$$

In [7]:
eq1 = linalg.solve(A,b)
eq2 = linalg.solve(A,c)
eq3 = linalg.solve(A,d)

print(eq1)
print(eq2)
print(eq3)

[-15.33189031 -24.00998148  40.02675108  15.24193293   4.89008792]
[ -7.72469812 -11.6354722   20.86796131   7.93343031   1.55909328]
[-2.57374569 -4.00256301  7.93409587  2.56007481  1.25709881]


**Answer:** A2.py

**Question C:** Solve the same equation systems as above using `linalg.lu_factor()` and `linalg.lu_solve()`. What is the benefit of this approach?

In [9]:
LU, piv = linalg.lu_factor(A)
eq1 = linalg.lu_solve((LU,piv),b)
eq2 = linalg.lu_solve((LU,piv),c)
eq3 = linalg.lu_solve((LU,piv),d)
print(eq1)
print(eq2)
print(eq3)

[-15.33189031 -24.00998148  40.02675108  15.24193293   4.89008792]
[ -7.72469812 -11.6354722   20.86796131   7.93343031   1.55909328]
[-2.57374569 -4.00256301  7.93409587  2.56007481  1.25709881]


**Answer:** A3.py

## Solving matrix equations II

In [10]:
F = np.array([[2.0, 1.0, -1.0], [-3.0, -1.0, 2], [-2.0, 1.0, 2.0]])
e = np.array([8.0, -11.0, -3.0])

**Question:** Use the function `gauss_jordan()` in the `numecon_linalg` module located in this folder to solve

$$
Fx = e
$$

In [16]:
# write your code here
import numecon_linalg 
Y = np.column_stack((F,e))
numecon_linalg.gauss_jordan(Y)
print('solution',Y[:,-1])



solution [ 2.  3. -1.]


In [17]:
eq4 = linalg.solve(F,e)
print(eq4)

[ 2.  3. -1.]


**Answer:** see A4.py

## Symbolic

**Question A:** Find

$$
\lim_{x \rightarrow 0} \frac{\sin(x)}{x}
$$

and

$$
\frac{\partial\sin(2x)}{\partial x} 
$$

In [18]:
# write your code here
# take limit using sympy
x = sm.symbols('x')
f = sm.sin(x)/x
sm.limit(f,x,0)



1

In [19]:
# derivative using sympy
f2 = sm.sin(2*x)/x
sm.diff(f2,x)

2*cos(2*x)/x - sin(2*x)/x**2

**Answer:** A5.py

**Question B:** Solve the equation

$$ 
\frac{\sin(x)}{x} = 0
$$

In [22]:
# solve equation using sympy
f3 = sm.sin(x)/x
eq4 = sm.Eq(f3,0)
sm.solve(eq4,x)

[pi]

**Answer:** A6.py

# Problem: Solve the Solow model

## Introduction

Consider the **standard Solow-model** where:

1. $K_t$ is capital2
2. $L_t$ is labor (growing with a constant rate of $n$)
3. $A_t$ is technology (growing with a constant rate of $g$)
4. $Y_t = F(K_t,A_tL_t)$ is GDP

**Saving** is a constant fraction of GDP

$$ 
S_t = sY_t,\,s\in(0,1)
$$

such that **capital accumulates** according to

$$
K_{t+1}=S_{t}+(1-\delta)K_{t}=sF(K_{t},A_{t}L_{t})+(1-\delta)K_{t}, \delta \in (0,1)
$$

The **production function** has **constant-return to scale** such that

$$
\frac{Y_{t}}{A_{t}L_{t}}=\frac{F(K_{t},A_{t}L_{t})}{A_{t}L_{t}}=F(\tilde{k}_{t},1)\equiv f(\tilde{k}_{t})
$$

where $\tilde{k}_t = \frac{K_t}{A_{t}L_{t}}$ is the technology adjusted capital-labor ratio.

The **transition equation** then becomes

$$
\tilde{k}_{t+1}= \frac{1}{(1+n)(1+g)}[sf(\tilde{k}_{t})+(1-\delta)\tilde{k}_{t}]
$$

If the **production function** is **Cobb-Douglas** then

$$
F(K_{t},A_{t}L_{t})=K_{t}^{\alpha}(A_{t}L_{t})^{1-\alpha}\Rightarrow f(\tilde{k}_{t})=\tilde{k}_{t}^{\alpha}
$$

If it is **CES** (with $\beta < 1, \beta \neq 0$) then

$$
F(K_{t},A_{t}L_{t})=(\alpha K_{t}^{\beta}+(1-\alpha)(A_{t}L_{t})^{\beta})^{\frac{1}{\beta}}\Rightarrow f(\tilde{k}_{t})=(\alpha\tilde{k}_{t}^{\beta}+(1-\alpha))^{\frac{1}{\beta}}
$$

## Steady state

Assume the production function is **Cobb-Douglas**.

**Question A:** Use **sympy** to find an analytical expression for the steady state, i.e. solve

$$
\tilde{k}^{\ast}= \frac{1}{(1+n)(1+g)}[sf(\tilde{k}^{\ast})+(1-\delta)\tilde{k}^{\ast}]
$$

In [23]:
k = sm.symbols('k')
alpha = sm.symbols('alpha')
delta = sm.symbols('delta')
s = sm.symbols('s')
g = sm.symbols('g')
n = sm.symbols('n')

In [31]:
# find steady state using sympy
f = k**alpha
eq5 = sm.Eq(1/((1+n)*(1+g))*(s*f+(1-delta)*k),k)
ss = sm.solve(eq5,k)[0]
ss

((delta + g*n + g + n)/s)**(1/(alpha - 1))

**Answer:** see A7.py

**Question B:** Turn you solution into a Python function called as `ss_func(s,g,n,delta,alpha)`. 

In [36]:
# turn ss into a lambda function
ss_func = sm.lambdify((alpha,delta,s,g,n),ss)
ss_func(s = 0.2,
g = 0.02,
n = 0.01,
alpha = 1/3,
delta = 0.1)


1.903831539231319

**Answer:** A8.py

**Question C**: Find the steady state numerically using root-finding with `optimize.root_scalar`.

In [40]:
s = 0.2
g = 0.02
n = 0.01
alpha = 1/3
delta = 0.1

# find the steady state numerically using root-finding with optimize.root_scalar
def f(s,g,n,alpha,delta):
    """ function for root-finding """
    res = optimize.root_scalar(lambda k: 1/((1+n)*(1+g))*(s*k**alpha+(1-delta)*k)-k, x0=0.5, x1=0.6)
    return res
f(s,g,n,alpha,delta)


      converged: True
           flag: 'converged'
 function_calls: 8
     iterations: 7
           root: 1.9038315392313219

**Answer:** A9.py

**Question D:** Now assume the production function is CES. Find the steady state for $k$ for the various values of $\beta$ shown below.

In [62]:
betas = [-0.5,-0.25,-0.1,-0.05,0.05,0.1,0.25,0.5]
beta = [0]
f_ces = lambda k_ces: (alpha*k_ces**beta+(1-alpha))**(1/beta)
obj_ces = lambda k_ces: k_ces - (s*f_ces(k_ces) + (1-delta)*k_ces)/((1+g)*(1+n))

In [63]:
# Find ss for different values of beta for the CES production function using root-finding
for beta in betas:
    print(f'for beta {beta} the steady state for k is',optimize.root_scalar(obj_ces,bracket=[0.1,100],x0=betas).root)   

    

for beta -0.5 the steady state for k is 1.8471297000972984
for beta -0.25 the steady state for k is 1.873383262758588
for beta -0.1 the steady state for k is 1.8910856397655083
for beta -0.05 the steady state for k is 1.8973581025712734
for beta 0.05 the steady state for k is 1.9105159729244352
for beta 0.1 the steady state for k is 1.917422132817728
for beta 0.25 the steady state for k is 1.9395902733676993
for beta 0.5 the steady state for k is 1.9822334997701418


**Answer:** A10.py   